apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ciem-audit-pvc
  namespace: ciem
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-pvc
  namespace: ciem
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamole-recordings-pvc
  namespace: ciem
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
